services:
  postgres:
    image: postgres:16
    container_name: tdc_postgres
    environment:
      POSTGRES_USER: tdc
      POSTGRES_PASSWORD: tdc_password
      POSTGRES_DB: tdc_db
    ports:
      - "5432:5432"
    volumes:
      - tdc_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: tdc_redis
    ports:
      - "6379:6379"

volumes:
  tdc_pgdata:
